<?php

namespace App\Traits;
use App\Services\MarketService;

trait AuthorizesMarketRequests{
    
    public function resolveAuthorization(&$queryParams, &$formParams, &$headers)
    {
        $accessToken = $this->resolveAccessToken();
        $headers['Authorization'] = $accessToken;
    }

    public function resolveAccessToken()
    {
        return 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRmM2U1MWEwOGNjZDdkOTdiYjRkODEyZTdlMTRlNGM4ZDI1ZThlZThhNzVjM2FkYjQwYzAzMGU1YWVhYWJhZjVhMDQxZTk2ZWU5YzRkZGY1In0.eyJhdWQiOiIyIiwianRpIjoiZGYzZTUxYTA4Y2NkN2Q5N2JiNGQ4MTJlN2UxNGU0YzhkMjVlOGVlOGE3NWMzYWRiNDBjMDMwZTVhZWFhYmFmNWEwNDFlOTZlZTljNGRkZjUiLCJpYXQiOjE1Njk5NjEwNzEsIm5iZiI6MTU2OTk2MTA3MSwiZXhwIjoxNjAxNTgzNDcxLCJzdWIiOiIxMTIzIiwic2NvcGVzIjpbInB1cmNoYXNlLXByb2R1Y3QiLCJtYW5hZ2UtcHJvZHVjdHMiLCJtYW5hZ2UtYWNjb3VudCIsInJlYWQtZ2VuZXJhbCJdfQ.oyfYphY6lAGY0eQyrxiwHZ4gGy6Yjty3sWdomYKWXcDTRv0DRC6dObB15ADy8sTGwsHPOVGYtT9sKdJ9yYrfHmktaMvqVFuxtTDQw4sXDWugrho6fpcgeN0uSnRePia6celX4op3B-GICMOi_Xlsv0SA5kOnpH2z7rf14QuVwm2MYUz5ixXIyIt1wZfCpSHBcpCmU-S99zrXiyoCXwe8vfbTBufQdS_OWU7nxQxSG1QkQGwd0VEilOKsUgFzk33-0MT3GlCitH-R3RYW4gdsX3w7cXtLfo427CdzVCPaJ-BBFLm_cf8_zKBosvJrfdh-A9AIbXhOBQcNHAMjR7_-iy4DSHuc3ZTm8gKZNJaTLbUqZvKT9q6MNJLcA19xg_1rTb4-a6GgYSfYR4wRUUqv041UcjiGYD5szRBnpJoPlxwyC0H0t5rHx4lEVIup3INnBG3zjbAXqW2e4uiVb9WimyULS0y8v3rv6EeSkG5T_NAfaXdERvutVAPpeOrCMVYcblrrR_1e-_-k2XbPAfBJdQ1qsPymxfgA72JczQGh2hXqSs7l2b-vu_oxXmaGmiKq9mfYkU3IBaKP7olQaiJPLEuq8blzCBomv_7uImg-G9xRTIfZZfj3ZMfWbzbSVLwh-GOhhFVt5tgyM_7rdslZ-jlzvml0irjAF_i99wmwaIA';
    }
    
}